version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: snippetboxdb
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: snippetbox
    ports:
      - "7000:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
